### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Depechie** [commuty-net/parking-access-api-client#1]
I'm trying to to use the package, but any method after building the rest client will result in:

```
CredentialsException: Impossible to retrieve a token: Wrong credentials
```

Although the mobile app and web versions with the same username / password work.
Any idea?

**Comment by looorent** [comment]
Hi @Depechie ,

This API is designed for use by Access Control integrators and is not intended for direct end-user access. However, if your organization requires access to this API, please reach out to us at support@commuty.net, and we will be happy to assist you with your request.
